name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Installer les dépendances du backend
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # 4. Recréer le fichier .env dans /server
      - name: Create .env for backend
        working-directory: ./server
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "DB_NAME=letsjam" >> .env
          echo "DB_PORT=3306" >> .env
          echo "PORT=5000" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env

      # 5. Installer les dépendances du frontend
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # 6. Démarrer le backend
      - name: Start backend
        working-directory: ./server
        run: npm run dev &
        env:
          PORT: 5000

      # 7. Démarrer le frontend
      - name: Start frontend
        working-directory: ./client
        run: npm run dev &
        env:
          PORT: 5173
          VITE_API_URL: http://localhost:5000

      # 8. Attendre que le frontend soit prêt
      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-for-netlify-action@v1
        with:
          url: "http://localhost:5173"
          timeout: 60

      # 9. Lancer les tests Cypress
      - name: Run Cypress tests
        working-directory: ./client
        run: npx cypress run
